services:
  deepseek:
    build: .
    container_name: deepseek
    ports:
      - 80:8000  
    depends_on:
      - redis
    restart: always
    x-tinkr:
      cpu: 512
      memory: 512
      environment:
        - SECRET_KEY=random
        - OPENAI_API_KEY=random
        - CHAT_GPT_API_KEY=random
        - REDIS_HOST=<hostname:redis>
      network:
        public: true  # Indicates this service is accessible in public subnets
      ports:
        deepseek-8000:
          port: 8000
          protocol: http
          public: true
          healthcheck:
            timeout: 10
            interval: 30
            path: /
            retries: 3
            success_code: 200-399
    environment:
      - SECRET_KEY=SECRET_KEY
      - OPENAI_API_KEY=SECRET_KEY
      - CHAT_GPT_API_KEY=SECRET_KEY
      - REDIS_HOST=localhost
    networks:
      - deepseek_network
      

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    x-tinkr:
      cpu: 512
      memory: 512
      network:
        public: false
      ports:
        redis:
          port: 6379
          protocol: tcp
          public: false
    networks:
      - deepseek_network

networks:
  deepseek_network:
    driver: bridge

volumes:
  db_data:
  wp_data:
